In [1]:
#Let's import the librarys
import nltk
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models import Word2Vec
from nltk.corpus import stopwords
import re

In [2]:
#Get the paragraph
paragraph="""Simplicity is the second most heroic quality that Gandhi demonstrated. Gandhi believed in living a simple life. He wanted a simple life, with only the necessities that he needed. Even though he was a barrister (a lawyer), he had no arrogance. He dressed like a poor person and he only wore clothes that were homespun, made out of khadi (cotton). He was a vegetarian and then became a fruitarian; many days he would go without eating and would not complain. He was also a man of truth because everything he did and said, he did it with truth. Because he believed in truth, he wrote a book titled, The Story of My Experiments with Truth. Moreover, even though he did many heroic things, he claimed to be an average man: "I claim to be no more than an average man with less than average ability" (pg 112). This quote tells the readers that he did not want to be known as Gandhi, he did not want everyone worshiping him, and he was just proving that he is an average person like others. In addition, what made him a hero can make anyone a hero, only if they have the will to do the right thing and if they believe in truth, nonviolence and creating peace among others. As a result, Gandhi believed that simplicity and truth can make anyone a hero."""

In [3]:
paragraph

'Simplicity is the second most heroic quality that Gandhi demonstrated. Gandhi believed in living a simple life. He wanted a simple life, with only the necessities that he needed. Even though he was a barrister (a lawyer), he had no arrogance. He dressed like a poor person and he only wore clothes that were homespun, made out of khadi (cotton). He was a vegetarian and then became a fruitarian; many days he would go without eating and would not complain. He was also a man of truth because everything he did and said, he did it with truth. Because he believed in truth, he wrote a book titled, The Story of My Experiments with Truth. Moreover, even though he did many heroic things, he claimed to be an average man: "I claim to be no more than an average man with less than average ability" (pg 112). This quote tells the readers that he did not want to be known as Gandhi, he did not want everyone worshiping him, and he was just proving that he is an average person like others. In addition, wha

In [4]:
text=re.sub(r'\[[0-9]*\]'," ",paragraph)

In [5]:
text

'Simplicity is the second most heroic quality that Gandhi demonstrated. Gandhi believed in living a simple life. He wanted a simple life, with only the necessities that he needed. Even though he was a barrister (a lawyer), he had no arrogance. He dressed like a poor person and he only wore clothes that were homespun, made out of khadi (cotton). He was a vegetarian and then became a fruitarian; many days he would go without eating and would not complain. He was also a man of truth because everything he did and said, he did it with truth. Because he believed in truth, he wrote a book titled, The Story of My Experiments with Truth. Moreover, even though he did many heroic things, he claimed to be an average man: "I claim to be no more than an average man with less than average ability" (pg 112). This quote tells the readers that he did not want to be known as Gandhi, he did not want everyone worshiping him, and he was just proving that he is an average person like others. In addition, wha

In [6]:
text=re.sub(r'\s+'," ",text)
text

'Simplicity is the second most heroic quality that Gandhi demonstrated. Gandhi believed in living a simple life. He wanted a simple life, with only the necessities that he needed. Even though he was a barrister (a lawyer), he had no arrogance. He dressed like a poor person and he only wore clothes that were homespun, made out of khadi (cotton). He was a vegetarian and then became a fruitarian; many days he would go without eating and would not complain. He was also a man of truth because everything he did and said, he did it with truth. Because he believed in truth, he wrote a book titled, The Story of My Experiments with Truth. Moreover, even though he did many heroic things, he claimed to be an average man: "I claim to be no more than an average man with less than average ability" (pg 112). This quote tells the readers that he did not want to be known as Gandhi, he did not want everyone worshiping him, and he was just proving that he is an average person like others. In addition, wha

In [7]:
text=re.sub(r'\d'," ",text)
text

'Simplicity is the second most heroic quality that Gandhi demonstrated. Gandhi believed in living a simple life. He wanted a simple life, with only the necessities that he needed. Even though he was a barrister (a lawyer), he had no arrogance. He dressed like a poor person and he only wore clothes that were homespun, made out of khadi (cotton). He was a vegetarian and then became a fruitarian; many days he would go without eating and would not complain. He was also a man of truth because everything he did and said, he did it with truth. Because he believed in truth, he wrote a book titled, The Story of My Experiments with Truth. Moreover, even though he did many heroic things, he claimed to be an average man: "I claim to be no more than an average man with less than average ability" (pg    ). This quote tells the readers that he did not want to be known as Gandhi, he did not want everyone worshiping him, and he was just proving that he is an average person like others. In addition, wha

In [8]:
text=re.sub(r'\s+'," ",text)
text

'Simplicity is the second most heroic quality that Gandhi demonstrated. Gandhi believed in living a simple life. He wanted a simple life, with only the necessities that he needed. Even though he was a barrister (a lawyer), he had no arrogance. He dressed like a poor person and he only wore clothes that were homespun, made out of khadi (cotton). He was a vegetarian and then became a fruitarian; many days he would go without eating and would not complain. He was also a man of truth because everything he did and said, he did it with truth. Because he believed in truth, he wrote a book titled, The Story of My Experiments with Truth. Moreover, even though he did many heroic things, he claimed to be an average man: "I claim to be no more than an average man with less than average ability" (pg ). This quote tells the readers that he did not want to be known as Gandhi, he did not want everyone worshiping him, and he was just proving that he is an average person like others. In addition, what m

In [9]:
text=re.sub("[()]"," ",text)
text

'Simplicity is the second most heroic quality that Gandhi demonstrated. Gandhi believed in living a simple life. He wanted a simple life, with only the necessities that he needed. Even though he was a barrister  a lawyer , he had no arrogance. He dressed like a poor person and he only wore clothes that were homespun, made out of khadi  cotton . He was a vegetarian and then became a fruitarian; many days he would go without eating and would not complain. He was also a man of truth because everything he did and said, he did it with truth. Because he believed in truth, he wrote a book titled, The Story of My Experiments with Truth. Moreover, even though he did many heroic things, he claimed to be an average man: "I claim to be no more than an average man with less than average ability"  pg  . This quote tells the readers that he did not want to be known as Gandhi, he did not want everyone worshiping him, and he was just proving that he is an average person like others. In addition, what m

In [10]:
text=re.sub(r'\s+'," ",text)
text

'Simplicity is the second most heroic quality that Gandhi demonstrated. Gandhi believed in living a simple life. He wanted a simple life, with only the necessities that he needed. Even though he was a barrister a lawyer , he had no arrogance. He dressed like a poor person and he only wore clothes that were homespun, made out of khadi cotton . He was a vegetarian and then became a fruitarian; many days he would go without eating and would not complain. He was also a man of truth because everything he did and said, he did it with truth. Because he believed in truth, he wrote a book titled, The Story of My Experiments with Truth. Moreover, even though he did many heroic things, he claimed to be an average man: "I claim to be no more than an average man with less than average ability" pg . This quote tells the readers that he did not want to be known as Gandhi, he did not want everyone worshiping him, and he was just proving that he is an average person like others. In addition, what made 

In [11]:
text=text.lower()

In [12]:
#Convert in to sentence

sentence=nltk.sent_tokenize(text)
sentence

['simplicity is the second most heroic quality that gandhi demonstrated.',
 'gandhi believed in living a simple life.',
 'he wanted a simple life, with only the necessities that he needed.',
 'even though he was a barrister a lawyer , he had no arrogance.',
 'he dressed like a poor person and he only wore clothes that were homespun, made out of khadi cotton .',
 'he was a vegetarian and then became a fruitarian; many days he would go without eating and would not complain.',
 'he was also a man of truth because everything he did and said, he did it with truth.',
 'because he believed in truth, he wrote a book titled, the story of my experiments with truth.',
 'moreover, even though he did many heroic things, he claimed to be an average man: "i claim to be no more than an average man with less than average ability" pg .',
 'this quote tells the readers that he did not want to be known as gandhi, he did not want everyone worshiping him, and he was just proving that he is an average person

In [13]:
stemmer=PorterStemmer()
lemma=WordNetLemmatizer()

## Stemming

In [14]:
corpus=[]
for i in range(len(sentence)):
    words=nltk.word_tokenize(sentence[i])
    words=[stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    words=" ".join(words)
    corpus.append(words)

In [15]:
corpus

['simplic second heroic qualiti gandhi demonstr .',
 'gandhi believ live simpl life .',
 'want simpl life , necess need .',
 'even though barrist lawyer , arrog .',
 'dress like poor person wore cloth homespun , made khadi cotton .',
 'vegetarian becam fruitarian ; mani day would go without eat would complain .',
 'also man truth everyth said , truth .',
 'believ truth , wrote book titl , stori experi truth .',
 "moreov , even though mani heroic thing , claim averag man : `` claim averag man less averag abil '' pg .",
 'quot tell reader want known gandhi , want everyon worship , prove averag person like other .',
 'addit , made hero make anyon hero , right thing believ truth , nonviol creat peac among other .',
 'result , gandhi believ simplic truth make anyon hero .']

## Lemmatizing

In [16]:
corpus=[]
for i in range(len(sentence)):
    words=nltk.word_tokenize(sentence[i])
    words=[lemma.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    words=" ".join(words)
    corpus.append(words)

In [17]:
corpus

['simplicity second heroic quality gandhi demonstrated .',
 'gandhi believed living simple life .',
 'wanted simple life , necessity needed .',
 'even though barrister lawyer , arrogance .',
 'dressed like poor person wore clothes homespun , made khadi cotton .',
 'vegetarian became fruitarian ; many day would go without eating would complain .',
 'also man truth everything said , truth .',
 'believed truth , wrote book titled , story experiment truth .',
 "moreover , even though many heroic thing , claimed average man : `` claim average man le average ability '' pg .",
 'quote tell reader want known gandhi , want everyone worshiping , proving average person like others .',
 'addition , made hero make anyone hero , right thing believe truth , nonviolence creating peace among others .',
 'result , gandhi believed simplicity truth make anyone hero .']

## Bag of words

In [18]:
cv=CountVectorizer()
Sparce_matrix=cv.fit_transform(corpus).toarray()
Sparce_matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [19]:
Sparce_matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

## TF-IDF vector

In [20]:
tf=TfidfVectorizer()
matrix=tf.fit_transform(corpus).toarray()

In [21]:
matrix

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.44997649,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.30640487, 0.        , 0.        ,
        0.38644504, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.44997649, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.44997649,
        0.        , 0.38644504, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [22]:
matrix.shape

(12, 76)

In [30]:
## Word2Vec
corpus=[]
for i in range(len(sentence)):
    words=nltk.word_tokenize(sentence[i])
    words=[word for word in words if word not in stopwords.words('english')]
    corpus.append(words)

In [31]:
model=Word2Vec(corpus,min_count=1)

In [32]:
model

In [34]:
words=model.wv.vocab

In [39]:
vectors=model.wv['gandhi']
vectors

array([-1.5020125e-03,  1.4896428e-03,  3.3601255e-03, -4.5080087e-03,
       -2.1754210e-03,  4.0538395e-03, -3.3205186e-03, -8.2162360e-04,
        2.0908774e-03, -2.4427329e-03,  1.3380233e-03, -4.0129907e-03,
       -2.7272096e-03, -3.1212515e-03,  1.2530171e-03, -4.8528030e-03,
        4.4944170e-03, -6.8498403e-04, -3.3117472e-03,  4.4217021e-03,
       -1.8497738e-03, -2.8762352e-03, -2.2698292e-03, -4.5602228e-03,
        9.7153621e-04, -9.9360663e-04,  1.2250445e-03,  3.7205422e-03,
       -2.0822661e-03,  1.9122771e-03, -4.5814211e-03,  1.8723230e-04,
        3.3759598e-03,  2.5910179e-03,  4.5375479e-03,  1.7838872e-03,
       -1.3314834e-03, -2.7082900e-03, -4.4254912e-03, -4.7310004e-03,
       -3.4037069e-03, -1.6585245e-03,  2.8350765e-03, -1.3354635e-03,
        1.5783196e-03,  3.9833835e-03,  7.3771511e-04, -2.3851066e-03,
        2.9993693e-03, -1.5391000e-04, -4.2515835e-03,  1.4663902e-04,
        3.6742217e-03,  1.5457211e-03,  4.2802957e-03, -9.1564783e-04,
      

In [41]:
similar=model.wv.most_similar('gandhi')
similar

NameError: name 'simliar' is not defined